### ISSUE TITLE
MLB Integration Stopped Working

### ISSUE THREAD

**Issue by NRutt2005** [jazakrzewski/ha-mlb#2]
I updated to 2023.5.3 and my MLB integration stopped working. Any thoughts on what the issue is? Below is the error log.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mlb/__init__.py:65
Integration: MLB (documentation, issues)
First occurred: 9:31:52 PM (5 occurrences)
Last logged: 9:51:53 PM

Error setting up entry LA Dodgers for mlb
Error setting up entry Texas Rangers for mlb
Error setting up entry Boston Red Socks for mlb
Error setting up entry Atlanta Braves for mlb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mlb/__init__.py", line 65, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by jazakrzewski** [comment]
Just published release 0.3 which should resolve this issue
